spring:
  application:
    name: url-shortener
  datasource:
    url: jdbc:postgresql://localhost:5432/urlshortener
    driver-class-name: org.postgresql.Driver
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true